version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client

  postgres: #MUST MATCH WITH POOL HOST
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./server/database-data.sql:/docker-entrypoint-initdb.d/database-data.sql
